Bunch -> Webpack
I’m following https://gist.github.com/chrismccord/bb1f8b136f5a9e4abc0bfc07b832257e

~~Current~~ issues:

- SCSS changes aren’t reflected in the browser
- `ReferenceError: require is not defined` in the console, but JS still works. I get another error, `Error: Cannot find module 'web/static/js/app' from ‘/‘` on master, so this may be related to a pre-existing issue.

This helped me get SCSS working: https://elixirforum.com/t/phoenix-1-3-to-1-4-migrating-from-brunch-to-webpack/17820/4

And the `require()` script I had in application.html.eex doesn’t appear necessary and isn’t present in new phoenix 1.4 apps, so I’m not sure where it came from.